### ISSUE TITLE
Skipping optional dependency: fsevents: unsupported platform. wanted {arch: any} even though current is arch: x64? 

### ISSUE THREAD

**Issue by sorezzz** [css/csso-cli#10]

**Comment by YasharF** [comment]
I think that is just a warning since fsevents is not required for your system.  It has been known as a confusing warning due to the way npm handles the issue and is part of a series of discussions and PR to make related changes in npm.  See https://github.com/npm/npm/issues/17466 and the related items in that ticket.

**Comment by lahmatiy** [comment]
@YasharF Thank you for clarification!
`fsevents` is not a direct dependency of `csso-cli`, but through `chokidar` (i.e. `csso-cli` -> `chokidar` -> (optional) `fsevents`).
You can eliminate an installation of optional deps (and such warnings as well) with `--no-optional` argument for `npm install`.
